Veewee::Session.declare({
  :cpu_count =>   2.to_s,
  :memory_size=>  (2 * 1024).to_s,
  :disk_size =>   (32 * 1024).to_s,
  :disk_format => 'VDI',
  :hostiocache => 'on',
  :os_type_id => 'Ubuntu_64',
  :iso_file => "trusty-server-amd64.iso",
  :iso_src => "http://cdimage.ubuntu.com/ubuntu-server/daily/current/trusty-server-amd64.iso",
  :iso_md5 => '76c9a0183c3f0c34cb30b57a05af9ec3',
  :iso_download_timeout => "1000",
  :boot_wait => "4",
  :boot_cmd_sequence => [
    '<Esc><Esc><Enter>',
    '/install/vmlinuz noapic preseed/url=http://%IP%:%PORT%/preseed.cfg ',
    'debian-installer=en_US auto locale=en_US kbd-chooser/method=us ',
    'hostname=%NAME% ',
    'fb=false debconf/frontend=noninteractive ',
    'keyboard-configuration/modelcode=SKIP keyboard-configuration/layout=us keyboard-configuration/variant=us console-setup/ask_detect=false ',
    'initrd=/install/initrd.gz -- <Enter>'
  ],
  :kickstart_port => "7122",
  :kickstart_timeout => "10000",
  :kickstart_file => "preseed.cfg",
  :ssh_login_timeout => "10000",
  :ssh_user => "vagrant",
  :ssh_password => "vagrant",
  :ssh_key => "",
  :ssh_host_port => "7222",
  :ssh_guest_port => "22",
  :sudo_cmd => "echo '%p'|sudo -S sh '%f'",
  :shutdown_cmd => "shutdown -P now",
  :postinstall_files => [ "postinstall.sh"],
  :postinstall_timeout => "10000"
})
